modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="more_vanilla"
version="0.0.0.2.5"
displayName="more vanilla"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="happyleibniz"
description="try to be realistic"

[[dependencies.more_vanilla]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




